baseURL = "https://hugodoit.pages.dev"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
# website title
title = "LinhGo"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = false
# whether to use emoji code
enableEmoji = true

# ignore some build errors
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# theme
theme = "DoIt"
