# site description
description = "Journey of technology, learning, and life"
# site keywords
keywords = ["Technology", "Learning", "Sharing", "LinhGo"]
# App icon config
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "LinhGo"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
# Search config
[search]
  enable = true
  # type of search engine ("algolia", "fuse", "pagefind")
  type = "algolia"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 40
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [search.algolia]
    index = "en_index"
    appID = "5YGRNRQK1G"
    searchKey = "0ff6874805de24b84aa1d5ebccad56cd"
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false
  [search.pagefind]
    # https://pagefind.app/docs/search-config/#available-options
    # run `npx pagefind --site $YOUR_PUBLIC_DIR` after site build to create pagefind index
    termFrequency = 1.0
    pageLength = 0.75
    termSimilarity = 1.0
    termSaturation = 1.4
# Home page config
[home]
  # amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.webp"
    # URL the avatar links to
    avatarLinkURL = ""
    # title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page
    subtitle = "The journey of Technology, Learning, and Life."
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 7
# Social config in home page
[social]
  Angellist = ""
  Bandcamp = ""
  Behance = ""
  Bilibili = ""
  Bitbucket = ""
  BuyMeACoffee = ""
  Codepen = ""
  Deviantart = ""
  Devto = ""
  Douban = ""
  Dribbble = ""
  Email = "info@linhgo.com"
  Facebook = "LinhNC.9"
  Fivehundredpx = ""
  Flickr = ""
  Foursquare = ""
  FreeCodeCamp = ""
  Gitea = ""
  GitHub = "LinhNC"
  Gitlab = ""
  Goodreads = ""
  Googlescholar = ""
  Hackernews = ""
  Instagram = ""
  Jsfiddle = ""
  Keybase = ""
  Kickstarter = ""
  Ko-Fi = ""
  Lastfm = ""
  Liberapay = ""
  Linkedin = "LinhNC"
  Linktree = ""
  Matrix = ""
  Medium = ""
  Mix = ""
  Odnoklassniki = ""
  ORCID = ""
  Patreon = ""
  Paypal = ""
  Pinterest = ""
  QQ = ""
  QQGroup = ""
  Quora = ""
  Reddit = ""
  Researchgate = ""
  RSS = true
  Skype = ""
  Slidershare = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Stackoverflow = ""
  Steam = ""
  Strava = ""
  Telegram = "LinhNC9"
  Thingiverse = ""
  Tumblr = ""
  Twitch = ""
  Twitter = ""
  Vine = ""
  VK = ""
  Weibo = ""
  Whatsapp = ""
  Wordpress = ""
  Xing = ""
  XMPP = ""
  Youtubechannel = ""
  Youtubecustom = ""
  Youtubelegacy = ""
  Zhihu = ""
  Bluesky = ""
# Sponsor config
[sponsor]
  enable = true
  bio = "If you find this post helpful"
  link = "https://github.com/sponsors/linhnc"
  custom = "<div style='margin-top:-20px;display: flex; justify-content: center; align-items: center;'><a href=\"https://www.buymeacoffee.com/linhnc\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a></div>"
