# Privacy config (https://gohugo.io/configuration/privacy/)

# privacy of the Google Analytics (replaced by params.analytics.google)
[googleAnalytics]
  # ...
[x]
  enableDNT = true
[youtube]
  privacyEnhanced = true
